CREATE TABLE students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_number VARCHAR(32) NOT NULL,
    name VARCHAR(100) NOT NULL,
    gender VARCHAR(16),
    date_of_birth DATE,
    phone VARCHAR(32),
    email VARCHAR(255),
    enrollment_date DATE,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_students_student_number UNIQUE (student_number),
    CONSTRAINT ck_students_status CHECK (status IN ('ACTIVE', 'SUSPENDED', 'GRADUATED', 'WITHDRAWN'))
);
