CREATE TABLE user_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    role VARCHAR(16) NOT NULL,
    student_id BIGINT,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_user_accounts_username UNIQUE (username),
    CONSTRAINT uk_user_accounts_student_id UNIQUE (student_id),
    CONSTRAINT fk_user_accounts_student FOREIGN KEY (student_id) REFERENCES students (id),
    CONSTRAINT ck_user_accounts_role CHECK (role IN ('ADMIN', 'TEACHER', 'STUDENT')),
    CONSTRAINT ck_user_accounts_student_link CHECK (
        (role = 'STUDENT' AND student_id IS NOT NULL)
        OR (role IN ('ADMIN', 'TEACHER') AND student_id IS NULL)
    )
);

CREATE TABLE auth_tokens (
    token_hash VARCHAR(64) PRIMARY KEY,
    user_account_id BIGINT NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_auth_tokens_user_account FOREIGN KEY (user_account_id) REFERENCES user_accounts (id) ON DELETE CASCADE
);

CREATE INDEX idx_auth_tokens_user_account_id ON auth_tokens (user_account_id);
CREATE INDEX idx_auth_tokens_expires_at ON auth_tokens (expires_at);
