CREATE TABLE school_classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    entry_year INTEGER NOT NULL,
    homeroom_teacher_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_school_classes_year_name UNIQUE (entry_year, name),
    CONSTRAINT fk_school_classes_homeroom_teacher FOREIGN KEY (homeroom_teacher_id) REFERENCES user_accounts (id),
    CONSTRAINT ck_school_classes_entry_year CHECK (entry_year BETWEEN 1900 AND 2200)
);

CREATE INDEX idx_school_classes_homeroom_teacher_id ON school_classes (homeroom_teacher_id);
