CREATE TABLE student_class_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    school_class_id BIGINT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_class_assignments_student FOREIGN KEY (student_id) REFERENCES students (id),
    CONSTRAINT fk_class_assignments_class FOREIGN KEY (school_class_id) REFERENCES school_classes (id),
    CONSTRAINT ck_class_assignments_dates CHECK (end_date IS NULL OR end_date >= start_date)
);

CREATE INDEX idx_class_assignments_student_id ON student_class_assignments (student_id);
CREATE INDEX idx_class_assignments_class_id ON student_class_assignments (school_class_id);
CREATE INDEX idx_class_assignments_student_dates ON student_class_assignments (student_id, start_date, end_date);
