CREATE TABLE courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_code VARCHAR(16) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL UNIQUE,
    credits NUMERIC(3, 1) NOT NULL,
    status VARCHAR(16) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_courses_credits CHECK (credits BETWEEN 0.5 AND 30.0),
    CONSTRAINT ck_courses_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE INDEX idx_courses_status ON courses (status);
