CREATE TABLE course_offerings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL,
    class_id BIGINT NOT NULL,
    teacher_id BIGINT NOT NULL,
    academic_year INTEGER NOT NULL,
    semester VARCHAR(16) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_course_offerings_class_term_course UNIQUE (class_id, academic_year, semester, course_id),
    CONSTRAINT fk_course_offerings_course FOREIGN KEY (course_id) REFERENCES courses (id),
    CONSTRAINT fk_course_offerings_class FOREIGN KEY (class_id) REFERENCES school_classes (id),
    CONSTRAINT fk_course_offerings_teacher FOREIGN KEY (teacher_id) REFERENCES user_accounts (id),
    CONSTRAINT ck_course_offerings_academic_year CHECK (academic_year BETWEEN 1900 AND 2200),
    CONSTRAINT ck_course_offerings_semester CHECK (semester IN ('FIRST', 'SECOND'))
);

CREATE INDEX idx_course_offerings_course_id ON course_offerings (course_id);
CREATE INDEX idx_course_offerings_teacher_id ON course_offerings (teacher_id);
CREATE INDEX idx_course_offerings_term ON course_offerings (academic_year, semester);
