CREATE TABLE grades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    course_offering_id BIGINT NOT NULL,
    score NUMERIC(4, 1) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_grades_student_offering UNIQUE (student_id, course_offering_id),
    CONSTRAINT fk_grades_student FOREIGN KEY (student_id) REFERENCES students (id),
    CONSTRAINT fk_grades_course_offering FOREIGN KEY (course_offering_id) REFERENCES course_offerings (id),
    CONSTRAINT ck_grades_score CHECK (score BETWEEN 0.0 AND 100.0)
);

CREATE INDEX idx_grades_student_id ON grades (student_id);
CREATE INDEX idx_grades_course_offering_id ON grades (course_offering_id);
