CREATE TABLE attendance_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_offering_id BIGINT NOT NULL,
    session_date DATE NOT NULL,
    topic VARCHAR(200),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_attendance_sessions_offering_date UNIQUE (course_offering_id, session_date),
    CONSTRAINT fk_attendance_sessions_offering FOREIGN KEY (course_offering_id) REFERENCES course_offerings (id)
);

CREATE TABLE attendance_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attendance_session_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    status VARCHAR(16) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_attendance_records_session_student UNIQUE (attendance_session_id, student_id),
    CONSTRAINT fk_attendance_records_session FOREIGN KEY (attendance_session_id) REFERENCES attendance_sessions (id),
    CONSTRAINT fk_attendance_records_student FOREIGN KEY (student_id) REFERENCES students (id),
    CONSTRAINT ck_attendance_records_status CHECK (status IN ('PRESENT', 'LATE', 'EXCUSED', 'ABSENT'))
);

CREATE INDEX idx_attendance_sessions_date ON attendance_sessions (session_date);
CREATE INDEX idx_attendance_records_student_id ON attendance_records (student_id);
